name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Lint code
      run: |
        # Add linting when available
        echo "Linting will be added when ESLint is configured"

    - name: Type check
      run: npx tsc --noEmit

    - name: Test basic functionality
      run: |
        # Basic test without Canvas credentials
        echo "Testing basic server startup without credentials"
        timeout 10s node dist/src/server.js || true

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Check for secrets
      run: |
        # Basic check for common secret patterns
        if grep -r "canvas.*token.*=" . --exclude-dir=node_modules --exclude="*.md" --exclude=".env.example"; then
          echo "Warning: Potential hardcoded tokens found"
          exit 1
        fi
        echo "No hardcoded tokens detected"
